# .github/workflows/ci.yml
name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-build:
    name: Check Lint/Test/Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 21, 22]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint Check
        run: pnpm run lint

      - name: Build Check
        run: pnpm run build